<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
* Implements hook_help().
*/

function hello_world_with_service_help($route_name, RouteMatchInterface $route_match) {

	// The function help is a basic Drupal hook
	// to generate info help. 

switch ($route_name) {
case 'help.page.hello_world_with_service':
 $output = '';
 $output .= '<h3>' . t('About') . '</h3>';
 $output .= '<p>' . t('This is an second example module. We are creating a new Drupal module with a Service to custom the message.') . '</p>';

  return $output;

default:

}

}
